spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lh367960
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  #如果字段为null 统一不返回
#  jackson:
#    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell